name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    # 'with:' の中身を以下のように「board」と「shield」を直接指定する形に変えます
    with:
      board: nice_nano_v2
      shield: bault_left
